### ISSUE TITLE
Это не PriceComparator, это получился ToStringComparator

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/HouseService#5]
https://github.com/NailMukhametshin/HouseService/blob/384a16f6c18df53176b6fc7368ae33303b920b2a/src/main/java/ru/itpark/comparator/PriceComparator.java#L11

**Comment by NailMukhametshin** [comment]
@coursar, исправил в a07b6ab8fab42d49c6ddcc32342423aae5662365.
